---
title: "Data Visualization 1"
author: "Chris Qi"
date: "8/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 数据可视化第一部分
```{r}
plot(airquality)
```



```{r}
#绘制箱图（数值型变量）
boxplot(airquality$Temp) 
```

```{r}
boxplot(airquality$Temp, xlab="Temperature",ylab="F")
```

```{r}
#按月份，给每一个月的温度绘箱图
#month是分类变量
boxplot(Temp~Month,airquality,xlab="month", 
        ylab="Temperature (F)")
```

```{r}
plot(Wind~Temp,airquality)
```

```{r}
#with() 更简便的绘图函数，
# 再不用每个变量都引用数据集
with(airquality, plot(Wind~Temp))
title(main="wind and temp in NYC") #使用title进行修饰
```

```{r}
#另外一种方式添加标题，一样的结果
with(airquality, plot(Wind, Temp,
     main="wind and temp in NYC")) 
```

```{r}
#有用的 type="n"
with(airquality, plot(Wind, Temp,
                      main="Wind and Temp in NYC",
                      type="n"))
```

```{r}
with(airquality, plot(Wind, Temp,
                      main="Wind and Temp in NYC",
                      type="n"))
with(subset(airquality, Month==9), 
     points(Wind, Temp, col="red"))
```

```{r}
with(airquality, plot(Wind, Temp,
                      main="Wind and Temp in NYC",
                      type="n"))
with(subset(airquality, Month==9), 
     points(Wind, Temp, col="red"))
with(subset(airquality, Month==8), 
     points(Wind, Temp, col="blue"))
```

```{r}
with(airquality, plot(Wind, Temp,
                      main="Wind and Temp in NYC",
                      type="n"))
with(subset(airquality, Month==9), 
     points(Wind, Temp, col="red"))

with(subset(airquality, Month==8), 
     points(Wind, Temp, col="blue"))

with(subset(airquality, Month==7), 
     points(Wind, Temp, col="green"))
#完成了用不同的颜色表示不同的月份的点
```

```{r}
with(airquality, plot(Wind, Temp,
                      main="Wind and Temp in NYC",
                      type="n"))
with(subset(airquality, Month==9), 
     points(Wind, Temp, col="red"))

with(subset(airquality, Month==8), 
     points(Wind, Temp, col="blue"))

with(subset(airquality, Month==7), 
     points(Wind, Temp, col="green"))

with(subset(airquality, Month %in% c(5,6)), 
     points(Wind, Temp, col="black"))
```

```{r}
with(airquality, plot(Wind, Temp,
                      main="Wind and Temp in NYC",
                      type="n"))
with(subset(airquality, Month==9), 
     points(Wind, Temp, col="red"))

with(subset(airquality, Month==8), 
     points(Wind, Temp, col="blue"))

with(subset(airquality, Month==7), 
     points(Wind, Temp, col="green"))

with(subset(airquality, Month %in% c(5,6)), 
     points(Wind, Temp, col="black"))

fit<-lm(Temp~Wind, airquality) #拟合一个回归模型
abline(fit,lwd=2) #把回归线加进去

#加入图例，说明颜色含义
legend("topright", pch=1, #右上角，空心圆点
       col=c("red","blue","green","black"),
       legend=c("Sep","August","July","Other"))
#使用基本函数绘图，需要事先计划，运行很多函数，
#可以直观的反映我们绘图的逻辑
#图例要仔细一一对应
```


```{r}
par("bg") #背景颜色，默认白色
par("col") # 作图颜色，默认黑色
par("mar") #(bottom, left, top, right) 图片边距
par("mfrow") #默认一行一列
?par
```

```{r}
#通过改变全局参数，使面板中呈现多幅图片
par(mfrow = c(2,2)) #设置成2行两列
hist(airquality$Temp)
hist(airquality$Temp, freq = FALSE)
hist(airquality$Temp, freq = FALSE, col="blue")

hist(airquality$Temp, freq = FALSE, col="blue")
lines(density(airquality$Temp))

par(mfrow = c(1,1))
truehist(airquality$Temp)
lines(density(airquality$Temp))
```

```{r}
#两行一列
par(mfcol = c(2,1))
hist(airquality$Temp)
hist(airquality$Wind)
```

```{r}
#lattice 绘图实践
library(lattice) #需要先安装install.packages("lattice")
xyplot(Temp~Ozone, data=airquality) #散点图,还没有考察交互关系
airquality$Month<-factor(airquality$Month)
```

使用
```{r}
#查看不同月份下，前面两个变量的关系
xyplot(Temp~Ozone|Month, data=airquality,
       layout=c(5,1)) #画1行5列
```


绘制表示相关性的椭圆图

越椭圆相关性越高，高到变成一条线。越接近圆相关性越低，直到标准圆。颜色越深相关性越大，最大是1,最小的是0（绝对值），蓝色为正相关，红色为负相关。
```{r}
# Load the corrplot library for the corrplot() function
library(corrplot)

# Extract the numerical variables from UScereal
numericalVars <- UScereal[, 2:10]

# Compute the correlation matrix for these variables
corrMat <- cor(numericalVars)

# Generate the correlation ellipse plot
corrplot(corrMat, method = "ellipse")

```




---
还记得前面的鸡吗？我们来做个直方图，频率的，加一条密度曲线。
```{r eval=FALSE}
# Create index16, pointing to 16-week chicks
index16 <- which(ChickWeight$Time == 16)

# Get the 16-week chick weights
weights <- ChickWeight$weight[index16]

# Plot the normalized histogram
truehist(weights)

# Add the density curve to the histogram
lines(density(weights))
```

---
还记得前面的鸡吗？我们来做个直方图，频率的，加一条密度曲线。
```{r echo=FALSE}
# Create index16, pointing to 16-week chicks
index16 <- which(ChickWeight$Time == 16)

# Get the 16-week chick weights
weights <- ChickWeight$weight[index16]

# Plot the normalized histogram
truehist(weights)

# Add the density curve to the histogram
lines(density(weights))
```


