---
title: "Data Visualization 3"
author: "Chris Qi"
date: "8/5/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 数据可视化第三部分：ggplot2 之 ggplot
```{r}
#Data Visualization 3
library(ggplot2)
```

```{r}
#先传入数据集，然后是美学相关的层
ggplot(airquality, aes(Wind, Temp))
```

```{r}
#再加几何客体层
ggplot(airquality, aes(y=Wind, x=Temp))+
  geom_point()
```

```{r}
plot(airquality$Wind, airquality$Temp)
```


```{r}
#进一步修饰几何客体，颜色，透明度，大小
ggplot(airquality, aes(Wind, Temp))+
  geom_point(color="steelblue",alpha=0.4, size=3)
```

```{r}
#每个月用不同的颜色来表示
#将月份赋予颜色
#然后用美学属性的函数画出来
ggplot(airquality, aes(Wind, Temp))+
  geom_point(aes(color=factor(Month)),alpha=0.4, size=2)
```

```{r}
#添加统计信息层
ggplot(airquality, aes(Wind, Temp))+
  geom_point()+
  geom_smooth() #几何客体
```


```{r}
ggplot(airquality, aes(Ozone, Temp))+
  geom_point()+
  stat_smooth() #独立加统计信息，完全一样
```

```{r}
ggplot(airquality, aes(Wind, Temp))+
  stat_smooth() #可以没有点层
```

```{r}
ggplot(airquality, aes(Wind, Temp))+
  stat_smooth(method="lm") #自行设计：线性               
```

```{r}
ggplot(airquality, aes(Wind, Temp))+
  stat_smooth(method="lm", se=FALSE) #自行设计：线性，无置信区间               
```

```{r}
#给每个月份拟合一条回归线
ggplot(airquality, aes(Wind, Temp))+
  stat_smooth(method="lm", se=FALSE, aes(color=factor(Month)))
```

```{r}
#等效操作

ggplot(airquality, aes(Wind, Temp,col=factor(Month)))+
  stat_smooth(method="lm", se=FALSE)
```

```{r}
#基于整体数据进行拟合，group=1
ggplot(airquality, aes(Wind, Temp,
                       col=factor(Month),group=1))+
  stat_smooth(method="lm", se=FALSE)
```

```{r}
ggplot(airquality, aes(Wind, Temp,
                       col=factor(Month),group=1))+
  geom_point()+ #颜色还是在起作用，在点层  
  stat_smooth(method="lm", se=FALSE)
```

```{r}
ggplot(airquality, aes(Wind, Temp,
                       col=factor(Month)))+
  geom_point()+   
  stat_smooth(method="lm", se=FALSE,aes(group=1))
```

```{r}
#group 在统计层，允许我们继续添加统计层，并且按每个月拟合
ggplot(airquality, aes(Wind, Temp,
                       col=factor(Month)))+
  geom_point()+   
  stat_smooth(method="lm", se=FALSE,aes(group=1))+
  stat_smooth(method="lm", se=FALSE)  
```

```{r}
#使用scale color menu 来控制颜色
#加载颜色包
library(RColorBrewer)
```

```{r}
#从Daerk2中选5个颜色，外加黑色
myColors<-c(brewer.pal(5,"Dark2"), "black")
#看一看dark2是哪5种颜色
display.brewer.pal(5,"Dark2")
```

```{r}
#复制前一条代码，添加scale_color_manual
ggplot(airquality, aes(Wind, Temp,
                       col=factor(Month)))+
  geom_point()+   
  stat_smooth(method="lm", se=FALSE,aes(group=1,col="all"))+
  stat_smooth(method="lm", se=FALSE)+
  scale_color_manual("Month", values=myColors)
```

```{r}
#不同月份画在不同面板上
ggplot(airquality, aes(Wind, Temp,
                       col=factor(Month)))+
  geom_point()+ 
# stat_smooth(method="lm", se=FALSE,aes(group=1,col="all"))+
  stat_smooth(method="lm", se=FALSE)+
  scale_color_manual("Month", values=myColors)+
  facet_grid(.~Month)
```

```{r}
#改变与数据无关的主题背景
ggplot(airquality, aes(Wind, Temp,
                       col=factor(Month)))+
  geom_point()+   
  stat_smooth(method="lm", se=FALSE)+
  scale_color_manual("Month", values=myColors)+
  facet_grid(.~Month)+
  theme_classic()
```

###拓展内容

绘图颜色
```{r}

#colorRamp 用法
pal<-colorRamp(c("red", "blue")) #代表两个极端颜色
pal(0) #显示RGB对应值
pal(1)
pal(0.5) #混合颜色
```

```{r}
pal(seq(0,1,len=10))
```

```{r}
#colorRampPalette用法
pal<-colorRampPalette(c("red", "yellow")) #代表两个极端颜色
#返回的是颜色的16进制显示,不再是0-1之间数值
pal(1)
pal(2)
pal(15) # 返回15个颜色，red开始，yellow结束，其他在之间
```

install.packages("RColorBrewer")
```{r}
library(RColorBrewer)
```

```{r}
#如何结合RColorBrewer与colorRampPalette
cols<-brewer.pal(3,"Greens")
pal<-colorRampPalette(cols)
image(volcano,col=pal(20)) # 3个(绿)颜色端点，取值20个
```

```{r}
display.brewer.pal(3,"Greens")

display.brewer.pal(3,"Purples")
#我们学习了调色板，希望大家能用它作出高大上的图
```

小试牛刀
install.packages("car")
```{r}
library(car)
ggplot(Vocab, aes(x = education, fill = factor(vocabulary))) +
  geom_bar(position = "fill") +
  scale_fill_brewer() #默认的只有9种颜色，不够用，怎么办？
```

```{r}
# Definition of a set of blue colors
blues <- brewer.pal(9, "Blues") # from the RColorBrewer package

# 1 - Make a color range using colorRampPalette() and the set of blues
blue_range <- colorRampPalette(blues)

# 2 - Use blue_range to adjust the color of the bars, use scale_fill_manual()
ggplot(Vocab, aes(x = education, fill = factor(vocabulary))) +
  geom_bar(position = "fill") +
  scale_fill_manual(values = blue_range(11))
```


图形设备
默认使用屏幕设备
生成pdf
```{r}
pdf(file="myfig.pdf") 
with (airquality, plot(Wind, Temp,
                       main="Wind and Temp in NYC"))
dev.off()
```

生成png
```{r}
with (airquality, plot(Wind, Temp,
                       main="Wind and Temp in NYC"))
dev.copy(png,file="mycopy.png")
dev.off()
```

install.packages("carData")
install.packages("rgl")

```{r}
#3-D, picture 1
library(car)
scatter3d(prestige ~ income + education, id.n=3, data=Duncan)
```

```{r}
#3-D, picture 2
scatter3d(wt ~ hp+ mpg, id.n=3, data=mtcars)
```

使用jitter（错位），处理大量数据点造成的重叠问题
```{r}
# Scatter plot: clarity (x), carat (y), price (color)
ggplot(diamonds,aes(x=clarity,y=carat,col=price))+
geom_point()

# Dot plot with jittering
ggplot(diamonds,aes(x=clarity,y=carat,col=price))+
geom_point(position = "jitter")

#Another way
ggplot(diamonds,aes(x=clarity,y=carat,col=price))+
geom_jitter()
```

position:
在条形图中，使用不同的position来绘制不同的直方图，共有三种stack(默认)，fill, dodge
以mtcars数据为例，手动挡自动挡vs.气缸数量
```{r}
mtcars$am<-as.factor(mtcars$am)
# Draw a bar plot of cyl, filled according to am
ggplot(mtcars, aes(x = cyl, fill =am)) +
  geom_bar()

# Change the position argument to stack
ggplot(mtcars, aes(x = cyl, fill =am)) +
  geom_bar(position="stack")


# Change the position argument to fill
ggplot(mtcars, aes(x = cyl, fill =am)) +
  geom_bar(position="fill")


# Change the position argument to dodge
ggplot(mtcars, aes(x = cyl, fill =am)) +
  geom_bar(position="dodge")
```
直方图错位，半透明
```{r}
# 1 - The last plot form the previous exercise
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar(position = "dodge")

# 2 - Define posn_d with position_dodge()
posn_d <- position_dodge(0.2)

# 3 - Change the position argument to posn_d
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar(position = posn_d)

# 4 - Use posn_d as position and adjust alpha to 0.6
ggplot(mtcars, aes(x = cyl, fill = am)) +
  geom_bar(position = posn_d, alpha = 0.6)
```

案例分析：
泰坦尼克生还者数据
install.packages("titanic")
```{r}
library(titanic)
library(ggplot2)
# - Check the structure of titanic
titanic<-as.data.frame(titanic_train)
str(titanic)
titanic$Survived<-factor(titanic$Survived)
```

生还者分布
```{r}
ggplot(titanic, aes(x = Survived)) +
  geom_bar(position = "dodge")
```

男女分布
```{r}
ggplot(titanic, aes(x = Sex)) +
  geom_bar(position = "dodge")
```

船舱分布
```{r}
ggplot(titanic, aes(x = Pclass)) +
  geom_bar(position = "dodge")
```

```{r}
# - 男女在不同船舱的分布
ggplot(titanic, aes(x = Pclass, fill = Sex)) +
  geom_bar(position = "dodge")
```

```{r}
# - 男女的生还情况
ggplot(titanic, aes(x = Sex, fill = Survived )) +
  geom_bar(position = "fill")
```

```{r}
# - 不同船舱的人的生还情况
ggplot(titanic, aes(x = Pclass, fill = Survived)) +
  geom_bar(position = "fill")
```

```{r}
#  - Plot 2, add facet_grid() layer
ggplot(titanic, aes(x = Sex, fill = Survived)) +
  geom_bar(position = "fill")+
  facet_grid(.~Pclass)  
```




















