---
title: "Data Visualization HW2 Answer Key"
author: "Chris Qi"
date: "8/7/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

###Using qplot
ggplot2为我们提供了丰富又强悍的多种函数来绘图，其中的qplot()让我们可以快速简单粗暴的进行探索性分析（给自己看的），帮助我们很快了解数据特征。解释性分析则要交给ggplot()，调整细节，作出美观的图（给读者观众看）。

```{r}
par(mfrow=c(1,2))
# The old way
plot(mpg ~ wt, data = mtcars) # formula notation
with(mtcars, plot(wt, mpg)) # x, y notation
```

```{r}
# Using ggplot:
ggplot(mtcars, aes(x=wt, y=mpg)) +
  geom_point()
```

```{r}
# Using qplot:
qplot(y=mpg, x=wt, data = mtcars)
```

```{r}
# basic qplot scatter plot:
qplot(wt, mpg, data = mtcars)
```

```{r}
# Categorical variable mapped onto size:
# cyl
qplot(wt, mpg, data = mtcars, size = factor(cyl))
```

```{r}
# gear
qplot(wt, mpg, data = mtcars, size = factor(gear))
```

```{r}
# Continuous variable mapped onto col:
# hp
qplot(wt, mpg, data = mtcars,color = hp)
```

###Choosing geoms, part 1
qplot()会根据我们的数据类型，自动为我们选择一个几何图形geom，当然，我们也可以自己选。

```{r}
# qplot() with x only，自动为我们选了柱状图
qplot(factor(cyl), data = mtcars)
```

```{r}
# qplot() with x and y, 自动为我们选择散点图，但是...
qplot(factor(cyl), factor(vs), data = mtcars)
```

```{r}
#所以我们用jitter 来错位一下
qplot(factor(cyl), factor(vs), data = mtcars, geom = "jitter")
```

高大上，ggplot()

```{r}
# A scatter plot has been made for you
ggplot(mtcars, aes(x = wt, y = disp)) +
  geom_point()
```

```{r}
# 用不同颜色的散点来区分不同排量的车
ggplot(mtcars, aes(x = wt, y = mpg, col = disp)) +
  geom_point()
```

```{r}
# 用不同大小的散点来区分不同排量的车
ggplot(mtcars, aes(x = wt, y = mpg, size = disp)) +
  geom_point()
```

```{r}
#这行代码出现错误提示，为什么，是代码错了吗？
ggplot(mtcars, aes(x = wt, y = mpg, shape =disp)) +
  geom_point()
```

```{r}
# Explore the diamonds data frame with str()
str(diamonds)
```

```{r}
# Add geom_point() with +
ggplot(diamonds, aes(x = carat, y = price))+
geom_point()
```

```{r}
# Add geom_point() and geom_smooth() with +
ggplot(diamonds, aes(x = carat, y = price)) + 
geom_point() + 
geom_smooth()
```

来探索一下各种geom组合
```{r}
# 1 - The plot you created in the previous exercise
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point() +
  geom_smooth()
```

```{r}
# 2 - Copy the above command but show only the smooth line
ggplot(diamonds, aes(x = carat, y = price))  +
  geom_smooth()
```

```{r}
# 3 - Copy the above command and assign the correct value to col in aes()
ggplot(diamonds, aes(x = carat, y = price, color = clarity))  +
  geom_smooth()
```

```{r}
# 4 - Keep the color settings from previous command. Plot only the points with argument alpha.
ggplot(diamonds, aes(x = carat, y = price, color = clarity))  +
  geom_point(alpha = 0.4)
```

进一步理解ggplot的语法，作出精致的图
```{r}
# 先画一个底图，命名为dia_plot
dia_plot <- ggplot(diamonds, aes(x = carat, y = price))

# 用 geom_point()加一层点
dia_plot + geom_point()

# 修饰点层，加颜色区分不同透明度
dia_plot + geom_point(aes(color = clarity))
```

继续探索，添加拟合曲线geom_smooth()，关闭置信区间
```{r}
# 1 - The dia_plot object has been created for you
dia_plot <- ggplot(diamonds, aes(x = carat, y = price))

# 2 - Expand dia_plot by adding geom_point() with alpha set to 0.2
dia_plot <- dia_plot + geom_point(alpha=0.2)

# 3 - Plot dia_plot with additional geom_smooth() with se set to FALSE
dia_plot + geom_smooth(se = FALSE)

# 4 - Copy the command from above and add aes() with the correct mapping to geom_smooth()
dia_plot + geom_smooth(aes(col = clarity), se = FALSE)
```

基本作图 vs. ggplot2作图

```{r}
# Convert cyl to factor (don't need to change)
mtcars$cyl <- as.factor(mtcars$cyl)

# Example from base R (don't need to change)
plot(mtcars$wt, mtcars$mpg, col = mtcars$cyl)
abline(lm(mpg ~ wt, data = mtcars), lty = 2)
lapply(mtcars$cyl, function(x) {
  abline(lm(mpg ~ wt, mtcars, subset = (cyl == x)), col = x)
  })
legend(x = 5, y = 33, legend = levels(mtcars$cyl),
       col = 1:3, pch = 1, bty = "n")
```

```{r}
# Plot 1: add geom_point() to this command to create a scatter plot
ggplot(mtcars, aes(x = wt, y = mpg, col = cyl)) +
  geom_point()  # Fill in using instructions Plot 1

# Plot 2: include the lines of the linear models, per cyl
ggplot(mtcars, aes(x = wt, y = mpg, col = cyl)) +
  geom_point() + # Copy from Plot 1
  geom_smooth(method = "lm", se = FALSE)  # Fill in using instructions Plot 2

# Plot 3: include a lm for the entire dataset in its whole
ggplot(mtcars, aes(x = wt, y = mpg, col = cyl)) +
  geom_point() + # Copy from Plot 2
  geom_smooth(method = "lm", se = FALSE)+ # Copy from Plot 2
  geom_smooth(aes(group = 1), method = "lm", se = FALSE, linetype = 2)   # Fill in using instructions Plot 3
```

使用geom_bar()绘制柱状图，调用position的三种不同参数
```{r}
# The base layer, cyl.am, is available for you
# Add geom (position = "stack" by default)
cyl.am <- ggplot(mtcars, aes(x = factor(cyl), fill = factor(am)))
cyl.am +
  geom_bar()
```

```{r}
# Fill - show proportion
cyl.am + 
  geom_bar(position = "fill")  
```

```{r}
# Dodging - principles of similarity and proximity
cyl.am +
  geom_bar(position = "dodge") 
```

```{r}
# Clean up the axes with scale_ functions
val = c("#E41A1C", "#377EB8")
lab = c("Manual", "Automatic")
cyl.am +
  geom_bar(position = "dodge") +
  scale_x_discrete("Cylinders") + 
  scale_y_continuous("Number") +
  scale_fill_manual("Transmission", 
                    values = val,
                    labels = lab) 
```

数据点太多，一坨坨的颜色，怎么破？
```{r}
# Scatter plot: carat (x), price (y), clarity (color)
ggplot(diamonds,aes(x=carat,y=price,col=clarity))+
geom_point()
```

```{r}
#修改透明度
# Adjust for overplotting
ggplot(diamonds,aes(x=carat,y=price,col=clarity))+
geom_point(alpha=0.5)
```

```{r}
#透明度，重量，价格
# Scatter plot: clarity (x), carat (y), price (color)
ggplot(diamonds,aes(x=clarity,y=carat,col=price))+
geom_point(alpha=0.5)
```

```{r}
# Dot plot with jittering
ggplot(diamonds,aes(x=clarity,y=carat,col=price))+
geom_point(alpha=0.5,position = "jitter")
```























